version: "3.9"
services:
  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:8.1.0
    command: --max_allowed_packet=3250585600 # Set max_allowed_packet to 256M (or any other value)
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
